### LINK DE LA API DE GRUAS RESPONDIENTES
@api = http://localhost:3001/gruasrespondientes

### LISTAR
GET {{api}}/get

### CREAR
POST {{api}}/create
Content-Type: application/json

{
    "idGrua": 3,
    "idSiniestro": 1
}

### LISTAR POR ID
GET {{api}}/getbid/2

### ELIMINAR POR ID
DELETE {{api}}/delete/4


### EDITAR POR ID
PUT {{api}}/update/2
Content-Type: application/json

{
    "idGrua": 3,
    "idSiniestro": 1
}