### LINK DE LA API DE GRUAS RESPONDIENTES
@api = http://localhost:3001/gruasrespondientes

### LISTAR
GET {{api}}/get

### CREAR
POST {{api}}/create
Content-Type: application/json

{
    "idCorralon": 2,
    "idGruaTipo": 1,
    "matricula": ""
}

### LISTAR POR ID
GET {{api}}/getbid/

### ELIMINAR POR ID
DELETE {{api}}/delete/1


### EDITAR POR ID
PUT {{api}}/update/3
Content-Type: application/json

{
    "idGrua": 3,
    "idCorralon":1,
    "idGruaTipo": 3,
    "matricula": "das87asd"
}